@extends('layouts.app')
@section('title','領取 '.$badge->name)
@section('content')
<div class="mx-auto max-w-md px-4 py-10"><article class="rounded-3xl border bg-white p-6 text-center shadow-sm"><img src="{{$badge->icon_url}}" class="mx-auto h-24 w-24 rounded-3xl object-cover"><p class="mt-4 text-sm font-medium text-indigo-600">{{$badge->issuer_name}} 發放</p><h1 class="mt-1 text-2xl font-bold">{{$badge->name}}</h1>@if($badge->description)<p class="mt-2 text-sm text-gray-600">{{$badge->description}}</p>@endif
@if(session('success'))<div class="mt-5 rounded-xl bg-green-50 p-4 text-sm text-green-700">{{session('success')}}</div>@endif @if(session('error'))<div class="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{{session('error')}}</div>@endif @if($errors->any())<div class="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{{$errors->first()}}</div>@endif
@if($badge->isAtCapacity())<p class="mt-5 rounded-xl bg-yellow-50 p-4 text-sm font-medium text-yellow-800">徽章數量已達到最大值</p>@else<p id="location-status" class="mt-5 text-sm text-gray-500">需要取得目前位置，確認你在發放區域內。</p><button id="claim-location" type="button" class="mt-4 min-h-12 w-full rounded-xl bg-indigo-600 px-5 font-medium text-white">驗證位置並領取</button><form id="location-form" method="POST" action="{{route('badge-drops.claim',$badge->claim_token)}}" class="hidden">@csrf<input name="lat" id="claim-lat"><input name="lng" id="claim-lng"><input name="accuracy" id="claim-accuracy"></form>@endif
</article></div>
<script>(()=>{const button=document.getElementById('claim-location');if(!button)return;const status=document.getElementById('location-status');button.addEventListener('click',()=>{if(!navigator.geolocation){status.textContent='此瀏覽器無法取得位置。';return}button.disabled=true;status.textContent='正在取得目前位置…';navigator.geolocation.getCurrentPosition(position=>{document.getElementById('claim-lat').value=position.coords.latitude;document.getElementById('claim-lng').value=position.coords.longitude;document.getElementById('claim-accuracy').value=position.coords.accuracy;document.getElementById('location-form').submit()},()=>{button.disabled=false;status.textContent='無法取得位置，請允許定位後再試一次。'},{enableHighAccuracy:false,timeout:15000,maximumAge:60000})})})();</script>
@endsection
