services:
    nginx:
        image: nginx:1.27-alpine
        ports: ["8080:80"]
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: [php, mysql]

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "app", "-papp" ]
            interval: 5s
            timeout: 3s
            retries: 20

    php:
        build:
            context: ./docker/php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            mysql:
                condition: service_healthy
volumes:
    dbdata:
