@php($badge=$badge??null)
@php($editing=$badge!==null)
<form method="POST" action="{{ $editing ? route('organizer.badges.update',$badge) : route('organizer.badges.store') }}" enctype="multipart/form-data" class="grid gap-4 sm:grid-cols-2" x-data="{locationEnabled:{{old('location_claim_enabled',$editing ? $badge->location_claim_enabled : false)?'true':'false'}},locating:false,lat:'{{old('claim_lat',$editing ? $badge->claim_lat : '')}}',lng:'{{old('claim_lng',$editing ? $badge->claim_lng : '')}}',locate(){if(!navigator.geolocation){alert('此瀏覽器無法取得位置');return}this.locating=true;navigator.geolocation.getCurrentPosition(p=>{this.lat=p.coords.latitude.toFixed(7);this.lng=p.coords.longitude.toFixed(7);this.locating=false},()=>{this.locating=false;alert('無法取得位置，請允許定位後再試一次。')},{enableHighAccuracy:false,timeout:15000,maximumAge:60000})}}">
    @csrf @if($editing) @method('PUT') @endif
    <div><label class="text-sm font-medium">Badge 名稱 *</label><input name="name" required value="{{old('name',$badge?->name??'')}}" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"></div>
    <div><label class="text-sm font-medium">活動／賽事名稱 *</label><input name="external_activity_name" required value="{{old('external_activity_name',$badge?->external_activity_name??'')}}" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"></div>
    <div><label class="text-sm font-medium">活動日期</label><input type="date" name="external_activity_date" value="{{old('external_activity_date',$badge?->external_activity_date?->format('Y-m-d')??'')}}" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"></div>
    <div><label class="text-sm font-medium">活動地點</label><input name="external_activity_location" value="{{old('external_activity_location',$badge?->external_activity_location??'')}}" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"></div>
    <div><label class="text-sm font-medium">限量數量</label><input type="number" min="1" name="max_supply" value="{{old('max_supply',$badge?->max_supply??'')}}" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 shadow-sm focus:border-indigo-500 focus:ring-indigo-500" placeholder="未填則不限制"></div>
    <div class="sm:col-span-2" x-data="{fileName:'{{ $editing && $badge->icon_path ? basename($badge->icon_path) : '尚未選擇圖片' }}',preview:'{{ $editing ? $badge->icon_url : '' }}'}">
        <label class="text-sm font-medium">Badge 圖示</label>
        <div class="mt-2 flex flex-col gap-3 rounded-2xl border border-dashed border-indigo-200 bg-indigo-50/60 p-4 sm:flex-row sm:items-center">
            <div class="flex items-center gap-3"><div class="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-white ring-1 ring-indigo-100"><img x-show="preview" :src="preview" alt="圖示預覽" class="h-full w-full object-cover"><svg x-show="!preview" class="h-7 w-7 text-indigo-300" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 16l4-4 4 4 3-3 5 5M14 8h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg></div><div class="min-w-0"><p class="truncate text-sm font-medium text-gray-700" x-text="fileName"></p><p class="mt-1 text-xs text-gray-500">JPG、PNG、WebP，最大 10MB</p></div></div>
            <label class="inline-flex min-h-11 cursor-pointer items-center justify-center rounded-xl bg-indigo-600 px-5 text-sm font-medium text-white hover:bg-indigo-500 sm:ml-auto">選擇圖片<input type="file" name="icon" accept="image/jpeg,image/png,image/webp" class="sr-only" @change="const file=$event.target.files[0];fileName=file?file.name:'尚未選擇圖片';preview=file?URL.createObjectURL(file):preview"></label>
        </div>
    </div>
    <div class="sm:col-span-2"><label class="text-sm font-medium">說明</label><textarea name="description" rows="3" class="mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">{{old('description',$badge?->description??'')}}</textarea></div>
    <div class="rounded-2xl border bg-gray-50 p-4 sm:col-span-2">
        <label class="flex items-center gap-2 font-medium"><input type="checkbox" name="location_claim_enabled" value="1" x-model="locationEnabled" class="rounded"> 開放掃描 QR Code 定位領取</label>
        <div x-show="locationEnabled" class="mt-4 grid gap-3 sm:grid-cols-3">
            <input name="claim_lat" x-model="lat" :required="locationEnabled" class="min-h-11 rounded-xl border border-gray-300 bg-white px-3 shadow-sm" placeholder="緯度">
            <input name="claim_lng" x-model="lng" :required="locationEnabled" class="min-h-11 rounded-xl border border-gray-300 bg-white px-3 shadow-sm" placeholder="經度">
            <select name="claim_radius_km" class="min-h-11 rounded-xl border border-gray-300 bg-white px-3 shadow-sm">@foreach([5,10,20,30] as $radius)<option value="{{$radius}}" @selected((string)old('claim_radius_km',$badge?->claim_radius_km??10)===(string)$radius)>{{$radius}} 公里</option>@endforeach</select>
            <button type="button" @click="locate()" class="min-h-11 rounded-xl border border-indigo-200 bg-white text-sm text-indigo-700 sm:col-span-3" x-text="locating?'正在取得位置…':'使用目前位置'"></button>
            <div class="sm:col-span-3"><label class="text-sm font-medium">可領取日期（選填）</label><input type="date" name="claim_date" value="{{old('claim_date',$badge?->claim_starts_at?->format('Y-m-d')??'')}}" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 shadow-sm"><p class="mt-1 text-xs text-gray-500">選擇後當天 00:00–23:59 可領取；留空則不限日期</p></div>
        </div>
    </div>
    <div class="flex gap-3 sm:col-span-2"><a href="{{route('organizer.badges.index')}}" class="inline-flex min-h-11 flex-1 items-center justify-center rounded-xl border text-sm">取消</a><button class="min-h-11 flex-1 rounded-xl bg-indigo-600 px-5 text-sm font-medium text-white">{{$editing?'儲存變更':'建立 Badge'}}</button></div>
</form>
