@extends('layouts.app')
@section('title','編輯組別')
@section('content')
<div class="mx-auto max-w-2xl px-4 py-8">
    <a href="{{ route('events.groups.index',$event) }}" class="text-sm text-indigo-600">← 返回組別</a>
    <h1 class="mt-2 text-2xl font-bold">編輯 {{ $group->name }}</h1>
    <form method="POST" action="{{ route('events.groups.update',[$event,$group]) }}" class="mt-6 grid gap-4 rounded-2xl border bg-white p-6" x-data="{ customWindow: {{ $group->usesCustomRegistrationWindow() ? 'true' : 'false' }} }">
        @csrf @method('PUT')
        @foreach(['name'=>'名稱','age_class'=>'年齡組','distance'=>'距離','arrow_count'=>'總箭數','quota'=>'名額','fee'=>'報名費'] as $field=>$label)<div><label class="text-sm font-medium">{{ $label }}</label><input name="{{ $field }}" value="{{ old($field,$group->$field) }}" @if($field === 'arrow_count') type="number" min="6" max="{{ $maxArrows }}" step="6" @endif class="mt-1 w-full rounded-xl border-gray-300">@if($field === 'arrow_count' && $maxArrows === 36)<p class="mt-1 text-xs text-amber-700">免費方案最多 36 箭。</p>@endif</div>@endforeach
        <div><label class="text-sm font-medium">弓種</label><select name="bow_type" class="mt-1 w-full rounded-xl border-gray-300">@foreach(['recurve'=>'反曲','compound'=>'複合','barebow'=>'光弓'] as $v=>$l)<option value="{{ $v }}" @selected($group->bow_type===$v)>{{ $l }}</option>@endforeach</select></div>
        <div><label class="text-sm font-medium">性別</label><select name="gender" class="mt-1 w-full rounded-xl border-gray-300">@foreach(['male'=>'男子','female'=>'女子','open'=>'公開'] as $v=>$l)<option value="{{ $v }}" @selected($group->gender===$v)>{{ $l }}</option>@endforeach</select></div>
        <div><label class="text-sm font-medium">每趟箭數</label><select name="arrows_per_end" class="mt-1 w-full rounded-xl border-gray-300"><option value="6" @selected($group->arrows_per_end===6)>6 箭</option><option value="3" @selected($group->arrows_per_end===3)>3 箭</option></select></div>
        <label class="inline-flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="use_custom_reg_window" value="1" x-model="customWindow" class="h-5 w-5 rounded">自訂此組報名時間</label>
        <div x-show="customWindow" class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-medium">報名開始</label><input type="datetime-local" name="reg_start" :required="customWindow" value="{{ optional($group->reg_start)->format('Y-m-d\TH:i') }}" class="mt-1 w-full rounded-xl border-gray-300"></div><div><label class="text-sm font-medium">報名截止</label><input type="datetime-local" name="reg_end" :required="customWindow" value="{{ optional($group->reg_end)->format('Y-m-d\TH:i') }}" class="mt-1 w-full rounded-xl border-gray-300"></div></div>
        <input type="hidden" name="is_team" value="0">
        @if($event->hasPlanFeature('team_competition'))<div class="rounded-xl border p-4"><label class="flex min-h-11 items-center gap-3 text-sm font-medium"><input type="checkbox" name="is_team" value="1" @checked(old('is_team',$group->is_team)) class="h-5 w-5 rounded">開放團體組隊</label><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="text-sm">團體類型<select name="team_type" class="mt-1 w-full rounded-xl border-gray-300"><option value="standard" @selected(old('team_type',$group->team_type)==='standard')>一般3人團體</option><option value="mixed" @selected(old('team_type',$group->team_type)==='mixed')>混雙2人團體</option></select></label><label class="text-sm">候補人數<select name="team_substitute_limit" class="mt-1 w-full rounded-xl border-gray-300"><option value="0">不使用候補</option><option value="1" @selected((int)old('team_substitute_limit',$group->team_substitute_limit)===1)>每隊1位候補</option></select></label></div><label class="mt-3 block text-sm">組隊截止<input type="datetime-local" name="team_formation_end" value="{{ old('team_formation_end', optional($group->team_formation_end)->format('Y-m-d\TH:i')) }}" class="mt-1 w-full rounded-xl border-gray-300"></label><p class="mt-1 text-xs text-gray-500">未設定時沿用組別或賽事報名截止。</p></div>@endif
        <button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-white">儲存</button>
    </form>
</div>
@endsection
