@extends('layouts.app')
@section('title','新增官方 Badge')
@section('content')
<div class="mx-auto max-w-3xl space-y-6 px-4 py-6 sm:px-6">
    <div><a href="{{route('admin.badges.index',['source'=>'official'])}}" class="text-sm text-indigo-600">← 返回官方 Badge</a><h1 class="mt-2 text-2xl font-bold">新增官方 Badge</h1></div>
    @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{$errors->first()}}</div>@endif
    <section class="rounded-2xl border bg-white p-5 shadow-sm sm:p-6">
        <form method="POST" action="{{route('admin.badges.store')}}" enctype="multipart/form-data" class="grid gap-4 sm:grid-cols-2" x-data="{locationEnabled:{{old('location_claim_enabled')?'true':'false'}},period:'{{old('claim_period','unlimited')}}',lat:'{{old('claim_lat')}}',lng:'{{old('claim_lng')}}',locating:false,fileName:'尚未選擇圖片',preview:'',locate(){if(!navigator.geolocation){alert('此瀏覽器無法取得位置');return}this.locating=true;navigator.geolocation.getCurrentPosition(p=>{this.lat=p.coords.latitude.toFixed(7);this.lng=p.coords.longitude.toFixed(7);this.locating=false},()=>{this.locating=false;alert('無法取得位置，請允許定位後再試一次。')})}}">@csrf
            <div><label class="text-sm font-medium">Badge 名稱 *</label><input name="name" required value="{{old('name')}}" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 px-3 shadow-sm"></div>
            <div><label class="text-sm font-medium">限量數量</label><input type="number" min="1" name="max_supply" value="{{old('max_supply')}}" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 px-3 shadow-sm" placeholder="未填則不限制"></div>
            <div class="sm:col-span-2"><label class="text-sm font-medium">說明</label><textarea name="description" rows="3" class="mt-1 w-full rounded-xl border border-gray-300 px-3 py-2 shadow-sm">{{old('description')}}</textarea></div>
            <div class="sm:col-span-2"><label class="text-sm font-medium">Badge 圖示</label><div class="mt-2 flex flex-col gap-3 rounded-2xl border border-dashed border-indigo-200 bg-indigo-50/60 p-4 sm:flex-row sm:items-center"><div class="flex items-center gap-3"><div class="flex h-16 w-16 items-center justify-center overflow-hidden rounded-2xl bg-white"><img x-show="preview" :src="preview" class="h-full w-full object-cover"><span x-show="!preview" class="text-2xl text-indigo-300">◇</span></div><div><p class="text-sm font-medium" x-text="fileName"></p><p class="text-xs text-gray-500">JPG、PNG、WebP，最大 10MB</p></div></div><label class="inline-flex min-h-11 cursor-pointer items-center justify-center rounded-xl bg-indigo-600 px-5 text-sm text-white sm:ml-auto">選擇圖片<input type="file" name="icon" accept="image/jpeg,image/png,image/webp" class="sr-only" @change="const f=$event.target.files[0];fileName=f?f.name:'尚未選擇圖片';preview=f?URL.createObjectURL(f):''"></label></div></div>
            <div class="rounded-2xl border bg-gray-50 p-4 sm:col-span-2"><label class="flex items-center gap-2 font-medium"><input type="checkbox" name="location_claim_enabled" value="1" x-model="locationEnabled" class="rounded"> 開放掃描 QR Code 定位領取</label><div x-show="locationEnabled" class="mt-4 grid gap-3 sm:grid-cols-3"><input name="claim_lat" x-model="lat" :required="locationEnabled" class="min-h-11 rounded-xl border border-gray-300 px-3" placeholder="緯度"><input name="claim_lng" x-model="lng" :required="locationEnabled" class="min-h-11 rounded-xl border border-gray-300 px-3" placeholder="經度"><select name="claim_radius_km" class="min-h-11 rounded-xl border border-gray-300 px-3"><option value="5">5 公里</option><option value="10" selected>10 公里</option><option value="20">20 公里</option><option value="30">30 公里</option></select><button type="button" @click="locate()" class="min-h-11 rounded-xl border border-indigo-200 bg-white text-sm text-indigo-700 sm:col-span-3" x-text="locating?'正在取得位置…':'使用目前位置'"></button><div class="sm:col-span-3"><label class="text-sm font-medium">領取期限</label><div class="mt-2 grid grid-cols-2 gap-2"><label class="flex min-h-11 items-center gap-2 rounded-xl border bg-white px-3"><input type="radio" name="claim_period" value="unlimited" x-model="period"> 不限日期</label><label class="flex min-h-11 items-center gap-2 rounded-xl border bg-white px-3"><input type="radio" name="claim_period" value="range" x-model="period"> 指定日期範圍</label></div></div><div x-show="period==='range'"><label class="text-xs text-gray-500">開始日期</label><input type="date" name="claim_start_date" value="{{old('claim_start_date')}}" :required="locationEnabled && period==='range'" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 px-3"></div><div x-show="period==='range'"><label class="text-xs text-gray-500">結束日期</label><input type="date" name="claim_end_date" value="{{old('claim_end_date')}}" :required="locationEnabled && period==='range'" class="mt-1 min-h-11 w-full rounded-xl border border-gray-300 px-3"></div><p x-show="period==='range'" class="self-end pb-3 text-xs text-gray-500">同一天即為單日領取</p></div></div>
            <div class="flex gap-3 sm:col-span-2"><a href="{{route('admin.badges.index',['source'=>'official'])}}" class="inline-flex min-h-11 flex-1 items-center justify-center rounded-xl border text-sm">取消</a><button class="min-h-11 flex-1 rounded-xl bg-indigo-600 text-sm font-medium text-white">建立官方 Badge</button></div>
        </form>
    </section>
</div>
@endsection
