@extends('layouts.app')
@section('title', 'Badge 監控')
@section('content')
<div class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6">
    <div><p class="text-xs font-semibold uppercase tracking-widest text-indigo-600">Platform Admin</p><h1 class="mt-1 text-2xl font-bold">Badge 監控</h1></div>
    @if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif @if(session('error'))<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{session('error')}}</div>@endif @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{$errors->first()}}</div>@endif
    <section class="rounded-2xl border bg-white p-5"><h2 class="font-semibold">建立官方限量 Badge</h2><form method="POST" action="{{route('admin.badges.store')}}" enctype="multipart/form-data" class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@csrf<input name="name" required class="rounded-xl border-gray-300" placeholder="Badge 名稱"><input type="number" min="1" name="max_supply" class="rounded-xl border-gray-300" placeholder="限量數量"><input type="file" name="icon" accept="image/jpeg,image/png,image/webp" class="rounded-xl border p-2"><button class="rounded-xl bg-indigo-600 px-4 text-white">建立官方 Badge</button><input name="description" class="rounded-xl border-gray-300 sm:col-span-2 lg:col-span-4" placeholder="說明（選填）"></form></section>
    <div class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs text-gray-500"><tr><th class="p-4">Badge／賽事</th><th class="p-4">狀態</th><th class="p-4">申請</th><th class="p-4">有效授予</th><th class="p-4 text-right">管理</th></tr></thead><tbody class="divide-y">
        @forelse($badges as $badge)<tr><td class="p-4"><div class="flex items-center gap-3"><img src="{{ $badge->icon_url }}" alt="" class="h-11 w-11 shrink-0 rounded-lg object-cover"><div><p class="font-semibold">{{ $badge->name }}</p><p class="text-xs text-gray-500">{{ $badge->issuer_name }}{{ $badge->display_activity_name ? '・'.$badge->display_activity_name : '' }}</p>@if($badge->max_supply)<p class="text-xs {{ $badge->isAtCapacity()?'text-yellow-700':'text-gray-500' }}">{{ $badge->isAtCapacity()?'徽章數量已達到最大值':'限量 '.$badge->active_awards_count.'／'.$badge->max_supply }}</p>@endif</div></div></td><td class="p-4"><span class="rounded-full px-2 py-1 text-xs {{ $badge->is_active ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700' }}">{{ $badge->is_active ? '正常' : '已停用' }}</span></td><td class="p-4">{{ $badge->claims_count }}</td><td class="p-4">{{ $badge->active_awards_count }}</td><td class="p-4 text-right"><div class="flex flex-col items-end gap-2">@if($badge->issuer_type==='platform'&&!$badge->isAtCapacity())<form method="POST" action="{{route('admin.badges.award',$badge)}}" class="flex gap-1">@csrf<input name="member" required class="w-44 rounded-lg border-gray-300 text-xs" placeholder="會員 UUID 或 Email"><button class="rounded-lg bg-indigo-600 px-2 text-xs text-white">發放</button></form>@endif<div class="flex gap-2">@if($badge->event)<a href="{{ route('organizer.events.badges.show', [$badge->event, $badge]) }}" class="rounded-lg border px-3 py-1.5 text-xs">查看紀錄</a>@endif<form method="POST" action="{{ route('admin.badges.toggle', $badge) }}">@csrf @method('PATCH')<button class="rounded-lg border px-3 py-1.5 text-xs {{ $badge->is_active ? 'text-red-600' : 'text-green-700' }}">{{ $badge->is_active ? '停用' : '重新啟用' }}</button></form></div></div></td></tr>
        @empty<tr><td colspan="5" class="p-8 text-center text-gray-500">尚無 Badge。</td></tr>@endforelse
    </tbody></table></div></div>
    {{ $badges->links() }}
</div>
@endsection
