@extends('layouts.app')
@section('title','主辦方資格申請')
@section('content')
@php($editable = !$profile || $profile->canEditApplication())
<div class="mx-auto max-w-3xl space-y-6 px-4 py-8 sm:px-6"><div><a href="{{ route('organizer.events.index') }}" class="text-sm text-indigo-600">← 主辦方中心</a><h1 class="mt-2 text-2xl font-bold">主辦方資格申請</h1><p class="mt-1 text-sm text-gray-500">資格核准後才能建立新賽事，每場賽事仍需另外送審。</p></div>
@if(session('success'))<div class="rounded-xl bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
@if($profile)<section class="rounded-2xl border p-5"><p class="text-sm text-gray-500">目前狀態</p><p class="mt-1 text-lg font-semibold">{{ ['draft'=>'申請草稿','pending'=>'平台審核中','changes_requested'=>'平台要求補件','approved'=>'已核准','rejected'=>'申請未通過','suspended'=>'資格已停權','legacy_review'=>'既有主辦方待審'][$profile->status] ?? $profile->status }}</p>@if($profile->public_review_note)<p class="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">平台說明：{{ $profile->public_review_note }}</p>@endif @if($profile->status==='pending')<form method="POST" action="{{ route('organizer.qualification.withdraw') }}" class="mt-4">@csrf<button class="text-sm text-red-600">撤回申請</button></form>@endif</section>@endif
@if($editable)<form method="POST" action="{{ route('organizer.qualification.update') }}" enctype="multipart/form-data" class="grid gap-4 rounded-2xl border bg-white p-6 sm:grid-cols-2">@csrf @method('PUT')
<div class="sm:col-span-2"><label class="text-sm font-medium">主辦單位名稱 *</label><input name="organization_name" required value="{{ old('organization_name',$profile?->organization_name) }}" class="mt-1 w-full rounded-xl border-gray-300"></div>
<div><label class="text-sm font-medium">類型 *</label><select name="organization_type" class="mt-1 w-full rounded-xl border-gray-300">@foreach(['individual'=>'個人','club'=>'俱樂部','association'=>'協會','school'=>'學校','company'=>'公司','other'=>'其他組織'] as $v=>$l)<option value="{{ $v }}" @selected(old('organization_type',$profile?->organization_type)===$v)>{{ $l }}</option>@endforeach</select></div>
<div><label class="text-sm font-medium">聯絡人 *</label><input name="contact_name" required value="{{ old('contact_name',$profile?->contact_name ?? auth()->user()->name) }}" class="mt-1 w-full rounded-xl border-gray-300"></div>
<div><label class="text-sm font-medium">聯絡 Email *</label><input type="email" name="contact_email" required value="{{ old('contact_email',$profile?->contact_email ?? auth()->user()->email) }}" class="mt-1 w-full rounded-xl border-gray-300"></div>
<div><label class="text-sm font-medium">聯絡電話 *</label><input name="contact_phone" required value="{{ old('contact_phone',$profile?->contact_phone) }}" class="mt-1 w-full rounded-xl border-gray-300"></div>
@foreach(['website'=>'官方網站','social_link'=>'官方社群','registration_number'=>'統一編號／組織識別'] as $field=>$label)<div><label class="text-sm font-medium">{{ $label }}</label><input name="{{ $field }}" value="{{ old($field,$profile?->$field) }}" class="mt-1 w-full rounded-xl border-gray-300"></div>@endforeach
@foreach(['experience'=>'過去主辦經歷','planned_events'=>'預計舉辦的賽事','application_reason'=>'申請原因 *'] as $field=>$label)<div class="sm:col-span-2"><label class="text-sm font-medium">{{ $label }}</label><textarea name="{{ $field }}" rows="3" @if($field==='application_reason') required @endif class="mt-1 w-full rounded-xl border-gray-300">{{ old($field,$profile?->$field) }}</textarea></div>@endforeach
<div class="sm:col-span-2"><label class="text-sm font-medium">驗證文件（PDF／圖片，最多 5MB）</label><input type="file" name="verification_document" accept=".pdf,.jpg,.jpeg,.png" class="mt-1 block w-full text-sm"></div>
<div class="sm:col-span-2 flex justify-end"><button class="rounded-xl bg-gray-900 px-5 py-2.5 text-sm text-white">儲存草稿</button></div></form>
@if($profile)<form method="POST" action="{{ route('organizer.qualification.submit') }}" class="text-right">@csrf<button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm text-white">正式送交平台審核</button></form>@endif
@endif
@if($profile && $profile->reviewLogs->isNotEmpty())<section class="rounded-2xl border bg-white p-5"><h2 class="font-semibold">申請紀錄</h2><div class="mt-3 divide-y">@foreach($profile->reviewLogs as $log)<div class="py-3 text-sm"><div class="flex justify-between"><span class="font-medium">{{ $log->action }}</span><time class="text-xs text-gray-500">{{ $log->created_at->format('Y-m-d H:i') }}</time></div>@if($log->public_note)<p class="mt-1 text-gray-600">{{ $log->public_note }}</p>@endif</div>@endforeach</div></section>@endif</div>
@endsection
