@extends('layouts.app')
@section('title',$profile->organization_name.' 主辦方審核')
@section('content')
@php($statusLabel = ['pending'=>'待審核','legacy_review'=>'既有待審','approved'=>'已核准','changes_requested'=>'待補件','rejected'=>'未通過','suspended'=>'已停權','draft'=>'草稿'][$profile->status] ?? $profile->status)
@php($statusClass = ['pending'=>'bg-yellow-100 text-yellow-800','legacy_review'=>'bg-yellow-100 text-yellow-800','approved'=>'bg-green-100 text-green-700','changes_requested'=>'bg-yellow-100 text-yellow-800','rejected'=>'bg-red-100 text-red-700','suspended'=>'bg-red-100 text-red-700','draft'=>'bg-gray-100 text-gray-600'][$profile->status] ?? 'bg-gray-100 text-gray-600')
<div class="mx-auto max-w-5xl space-y-5 px-4 py-6 sm:space-y-6 sm:px-6 sm:py-8"><div><a href="{{ route('admin.organizers.index') }}" class="inline-flex min-h-11 items-center text-sm font-medium text-indigo-600">← 主辦方列表</a><div class="flex flex-wrap items-center gap-2"><h1 class="break-words text-2xl font-bold">{{ $profile->organization_name }}</h1><span class="rounded-full px-3 py-1 text-xs font-medium {{ $statusClass }}">{{ $statusLabel }}</span></div><p class="mt-1 text-sm text-gray-500">{{ $profile->user?->display_name }}</p></div>@if(session('success'))<div class="rounded-xl bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<section class="grid gap-5 rounded-2xl border bg-white p-4 sm:grid-cols-2 sm:p-6"><div><p class="text-xs text-gray-500">類型</p><p class="mt-1">{{ $profile->organization_type }}</p></div><div><p class="text-xs text-gray-500">聯絡人</p><p class="mt-1 break-words">{{ $profile->contact_name }}・{{ $profile->contact_phone }}</p></div><div><p class="text-xs text-gray-500">Email</p><p class="mt-1 break-all">{{ $profile->contact_email }}</p></div><div><p class="text-xs text-gray-500">網站／社群</p><p class="mt-1 break-all">{{ $profile->website ?: $profile->social_link ?: '—' }}</p></div><div class="sm:col-span-2"><p class="text-xs text-gray-500">主辦經歷</p><p class="mt-1 whitespace-pre-line break-words">{{ $profile->experience ?: '—' }}</p></div><div class="sm:col-span-2"><p class="text-xs text-gray-500">預計賽事</p><p class="mt-1 whitespace-pre-line break-words">{{ $profile->planned_events ?: '—' }}</p></div><div class="sm:col-span-2"><p class="text-xs text-gray-500">申請原因</p><p class="mt-1 whitespace-pre-line break-words">{{ $profile->application_reason }}</p></div>@if($profile->verification_document_path)<div class="sm:col-span-2"><a href="{{ route('admin.organizers.document',$profile) }}" class="inline-flex min-h-11 w-full items-center justify-center rounded-xl border border-indigo-200 px-4 text-sm font-medium text-indigo-700 sm:w-auto">下載驗證文件</a></div>@endif</section>
@if(in_array($profile->status,['pending','legacy_review']))<form method="POST" action="{{ route('admin.organizers.review',$profile) }}" class="rounded-2xl border border-indigo-200 bg-indigo-50 p-4 sm:p-5">@csrf<h2 class="font-semibold">審核決定</h2><textarea name="public_note" rows="3" class="mt-3 w-full rounded-xl border-indigo-200" placeholder="給申請人的說明"></textarea><textarea name="internal_note" rows="3" class="mt-3 w-full rounded-xl border-indigo-200" placeholder="平台內部備註"></textarea><div class="mt-4 grid gap-2 sm:flex sm:justify-end"><button name="decision" value="approve" class="min-h-11 rounded-xl bg-green-600 px-4 text-sm font-medium text-white">核准</button><button name="decision" value="changes_requested" class="min-h-11 rounded-xl bg-amber-500 px-4 text-sm font-medium text-white">退回補件</button><button name="decision" value="reject" class="min-h-11 rounded-xl border border-red-200 bg-white px-4 text-sm font-medium text-red-600">拒絕</button></div></form>@endif
@if(in_array($profile->status,['approved','legacy_review']))<form method="POST" action="{{ route('admin.organizers.suspend',$profile) }}" class="rounded-2xl border bg-white p-4 sm:p-5">@csrf<h2 class="font-semibold text-red-700">停權</h2><input name="public_note" required class="mt-3 min-h-11 w-full rounded-xl border-gray-300" placeholder="停權原因（會員可見）"><input name="internal_note" class="mt-3 min-h-11 w-full rounded-xl border-gray-300" placeholder="內部備註"><button class="mt-4 min-h-11 w-full rounded-xl bg-red-600 px-4 text-sm font-medium text-white sm:w-auto">停權主辦方</button></form>@elseif($profile->status==='suspended')<form method="POST" action="{{ route('admin.organizers.restore',$profile) }}">@csrf<button class="min-h-11 w-full rounded-xl bg-green-600 px-4 text-sm font-medium text-white sm:w-auto">恢復主辦資格</button></form>@endif
<section class="rounded-2xl border bg-white p-4 sm:p-5"><h2 class="font-semibold">審核紀錄</h2><div class="mt-3 divide-y">@forelse($profile->reviewLogs as $log)<div class="py-3 text-sm"><div class="flex flex-col gap-1 sm:flex-row sm:justify-between"><span class="break-words font-medium">{{ $log->action }}・{{ $log->actor?->display_name ?? '系統' }}</span><time class="shrink-0 text-xs text-gray-500">{{ $log->created_at->format('Y-m-d H:i') }}</time></div>@if($log->public_note)<p class="mt-2 break-words">公開：{{ $log->public_note }}</p>@endif @if($log->internal_note)<p class="mt-1 break-words text-gray-500">內部：{{ $log->internal_note }}</p>@endif</div>@empty<p class="py-4 text-sm text-gray-500">尚無審核紀錄</p>@endforelse</div></section></div>
@endsection
