@extends('layouts.app')
@section('title',$profile->organization_name.' 主辦方審核')
@section('content')
<div class="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-6"><div><a href="{{ route('admin.organizers.index') }}" class="text-sm text-indigo-600">← 主辦方列表</a><h1 class="mt-2 text-2xl font-bold">{{ $profile->organization_name }}</h1><p class="mt-1 text-sm text-gray-500">{{ $profile->user?->display_name }}・{{ $profile->status }}</p></div>@if(session('success'))<div class="rounded-xl bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<section class="grid gap-4 rounded-2xl border bg-white p-6 sm:grid-cols-2"><div><p class="text-xs text-gray-500">類型</p><p>{{ $profile->organization_type }}</p></div><div><p class="text-xs text-gray-500">聯絡人</p><p>{{ $profile->contact_name }}・{{ $profile->contact_phone }}</p></div><div><p class="text-xs text-gray-500">Email</p><p>{{ $profile->contact_email }}</p></div><div><p class="text-xs text-gray-500">網站／社群</p><p>{{ $profile->website ?: $profile->social_link ?: '—' }}</p></div><div class="sm:col-span-2"><p class="text-xs text-gray-500">主辦經歷</p><p class="whitespace-pre-line">{{ $profile->experience ?: '—' }}</p></div><div class="sm:col-span-2"><p class="text-xs text-gray-500">預計賽事</p><p class="whitespace-pre-line">{{ $profile->planned_events ?: '—' }}</p></div><div class="sm:col-span-2"><p class="text-xs text-gray-500">申請原因</p><p class="whitespace-pre-line">{{ $profile->application_reason }}</p></div>@if($profile->verification_document_path)<div class="sm:col-span-2"><a href="{{ route('admin.organizers.document',$profile) }}" class="text-indigo-600">下載驗證文件</a></div>@endif</section>
@if(in_array($profile->status,['pending','legacy_review']))<form method="POST" action="{{ route('admin.organizers.review',$profile) }}" class="rounded-2xl border border-indigo-200 bg-indigo-50 p-5">@csrf<h2 class="font-semibold">審核決定</h2><textarea name="public_note" rows="2" class="mt-3 w-full rounded-xl border-indigo-200" placeholder="給申請人的說明"></textarea><textarea name="internal_note" rows="2" class="mt-2 w-full rounded-xl border-indigo-200" placeholder="平台內部備註"></textarea><div class="mt-3 flex justify-end gap-2"><button name="decision" value="approve" class="rounded-xl bg-green-600 px-4 py-2 text-sm text-white">核准</button><button name="decision" value="changes_requested" class="rounded-xl bg-amber-500 px-4 py-2 text-sm text-white">退回補件</button><button name="decision" value="reject" class="rounded-xl border border-red-200 bg-white px-4 py-2 text-sm text-red-600">拒絕</button></div></form>@endif
@if(in_array($profile->status,['approved','legacy_review']))<form method="POST" action="{{ route('admin.organizers.suspend',$profile) }}" class="rounded-2xl border bg-white p-5">@csrf<h2 class="font-semibold text-red-700">停權</h2><input name="public_note" required class="mt-3 w-full rounded-xl border-gray-300" placeholder="停權原因（會員可見）"><input name="internal_note" class="mt-2 w-full rounded-xl border-gray-300" placeholder="內部備註"><button class="mt-3 rounded-xl bg-red-600 px-4 py-2 text-sm text-white">停權主辦方</button></form>@elseif($profile->status==='suspended')<form method="POST" action="{{ route('admin.organizers.restore',$profile) }}">@csrf<button class="rounded-xl bg-green-600 px-4 py-2 text-sm text-white">恢復主辦資格</button></form>@endif
<section class="rounded-2xl border bg-white p-5"><h2 class="font-semibold">審核紀錄</h2><div class="mt-3 divide-y">@foreach($profile->reviewLogs as $log)<div class="py-3 text-sm"><div class="flex justify-between"><span class="font-medium">{{ $log->action }}・{{ $log->actor?->display_name ?? '系統' }}</span><time class="text-xs text-gray-500">{{ $log->created_at->format('Y-m-d H:i') }}</time></div>@if($log->public_note)<p class="mt-1">公開：{{ $log->public_note }}</p>@endif @if($log->internal_note)<p class="mt-1 text-gray-500">內部：{{ $log->internal_note }}</p>@endif</div>@endforeach</div></section></div>
@endsection
