@extends('layouts.app')
@section('title',$event->name.' 報名與報到')
@section('content')
<div class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6"><div><a href="{{ route('organizer.events.show',$event) }}" class="text-sm text-indigo-600">← 返回賽事工作台</a><h1 class="mt-2 text-2xl font-bold">報名與報到</h1><p class="mt-1 text-sm text-gray-500">{{ $event->name }}</p></div>
@if(session('success'))<div class="rounded-xl bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif @if(session('error'))<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ session('error') }}</div>@endif @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="grid gap-5 lg:grid-cols-[1fr_360px]"><section class="min-w-0 rounded-2xl border bg-white shadow-sm"><div class="border-b p-4"><form method="GET" class="flex flex-wrap gap-2"><input name="q" value="{{ request('q') }}" class="min-w-56 flex-1 rounded-xl border-gray-300 text-sm" placeholder="姓名或 Email"><select name="status" class="rounded-xl border-gray-300 text-sm"><option value="">全部狀態</option>@foreach(['registered'=>'已報名','checked_in'=>'已報到','withdrawn'=>'已退出','refunded'=>'已退款','no_show'=>'未到'] as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select><button class="rounded-xl border px-4 py-2 text-sm">篩選</button></form></div>
<form id="bulk-form" method="POST" action="{{ route('organizer.events.registrations.bulk',$event) }}" class="hidden">@csrf @method('PATCH')</form><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs text-gray-500"><tr><th class="p-3"><input type="checkbox" onclick="document.querySelectorAll('.reg-check').forEach(el=>el.checked=this.checked)"></th><th class="p-3">會員／組別</th><th class="p-3">狀態</th><th class="p-3">繳費</th><th class="p-3">操作</th></tr></thead><tbody class="divide-y">@forelse($registrations as $registration)<tr><td class="p-3"><input form="bulk-form" type="checkbox" class="reg-check rounded" name="registration_ids[]" value="{{ $registration->id }}"></td><td class="p-3"><p class="font-medium">{{ $registration->name }}</p><p class="text-xs text-gray-500">{{ $registration->event_group?->name }}・{{ $registration->email }}</p></td><td class="p-3">{{ ['registered'=>'已報名','checked_in'=>'已報到','withdrawn'=>'已退出','refunded'=>'已退款','no_show'=>'未到'][$registration->status] ?? $registration->status }}</td><td class="p-3">{{ $registration->paid?'已繳':'未繳' }}</td><td class="p-3"><form method="POST" action="{{ route('organizer.events.registrations.update',[$event,$registration]) }}" class="flex gap-1">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $registration->status }}"><input type="hidden" name="paid" value="{{ $registration->paid?0:1 }}"><button class="rounded-lg border px-2 py-1 text-xs">{{ $registration->paid?'標記未繳':'標記已繳' }}</button></form></td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-gray-500">尚無報名</td></tr>@endforelse</tbody></table></div><div class="flex flex-wrap gap-2 border-t p-4"><select form="bulk-form" name="status" class="rounded-xl border-gray-300 text-sm"><option value="checked_in">批次報到</option><option value="registered">恢復已報名</option><option value="no_show">標記未到</option><option value="withdrawn">標記退出</option><option value="refunded">標記退款</option></select><button form="bulk-form" class="rounded-xl bg-indigo-600 px-4 py-2 text-sm text-white">套用至選取項目</button></div></section>
<aside class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-semibold">掃會員 QR Code 報到</h2><video id="checkin-video" playsinline muted class="mt-3 hidden aspect-square w-full rounded-xl bg-gray-900 object-cover"></video><p id="checkin-status" class="mt-3 text-sm text-gray-500">可開啟相機掃描會員資料 QR Code，或輸入會員 UUID。</p><button id="start-camera" type="button" class="mt-3 w-full rounded-xl border px-4 py-2 text-sm">開啟相機</button><form id="checkin-form" method="POST" action="{{ route('organizer.events.registrations.check-in',$event) }}" class="mt-4">@csrf<input id="checkin-uuid" name="uuid" required class="w-full rounded-xl border-gray-300 text-sm" placeholder="會員 UUID"><button class="mt-2 w-full rounded-xl bg-green-600 px-4 py-2 text-sm text-white">確認報到</button></form></aside></div>{{ $registrations->links() }}</div>
<script>(()=>{const button=document.getElementById('start-camera'),video=document.getElementById('checkin-video'),status=document.getElementById('checkin-status'),input=document.getElementById('checkin-uuid');button.addEventListener('click',async()=>{if(!('BarcodeDetector'in window)){status.textContent='瀏覽器不支援相機掃描，請輸入 UUID。';return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});video.srcObject=stream;video.classList.remove('hidden');await video.play();const detector=new BarcodeDetector({formats:['qr_code']});button.classList.add('hidden');const scan=async()=>{const codes=await detector.detect(video);if(codes[0]){let value=codes[0].rawValue;try{value=new URL(value).pathname.split('/').filter(Boolean).pop()}catch(e){}input.value=value;stream.getTracks().forEach(t=>t.stop());document.getElementById('checkin-form').submit();return;}requestAnimationFrame(scan)};scan()}catch(e){status.textContent='無法開啟相機，請確認權限或手動輸入 UUID。'}})})();</script>
@endsection
