@extends('layouts.app')
@section('title', '建立賽事')
@section('content')
<style>
#event-create input:not([type=hidden]):not([type=radio]):not([type=checkbox]),#event-create select{border:1px solid #cbd5e1;background:#fff}#event-create input:focus,#event-create select:focus{border-color:#6366f1;box-shadow:0 0 0 3px rgb(99 102 241/.14);outline:none}#event-create .choice:has(input:checked){border-color:#6366f1;background:#eef2ff;color:#312e81}
</style>
<div class="mx-auto max-w-5xl px-4 py-6 sm:px-6 sm:py-8">
<header class="mb-6"><a href="{{ route('organizer.events.index') }}" class="inline-flex min-h-11 items-center text-sm font-medium text-indigo-600">← 我的主辦賽事</a><h1 class="mt-1 text-2xl font-bold">建立賽事</h1></header>
@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><p class="font-semibold">還有資料需要確認</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<nav class="mb-5 grid grid-cols-3 gap-2 text-center text-xs font-semibold sm:text-sm"><span data-progress="1" class="rounded-xl bg-indigo-600 px-2 py-3 text-white">1 基本資料</span><span data-progress="2" class="rounded-xl bg-gray-100 px-2 py-3 text-gray-500">2 組別設定</span><span data-progress="3" class="rounded-xl bg-gray-100 px-2 py-3 text-gray-500">3 確認建立</span></nav>
<form method="POST" action="{{ route('organizer.events.store') }}" id="event-create" class="space-y-5">@csrf
<input type="hidden" name="creation_plan" value="{{ $creationPlan }}"><input type="hidden" name="submit_mode" value="publish"><input type="hidden" name="check_in_enabled" value="0"><input type="hidden" name="reg_start" id="reg-start-value"><input type="hidden" name="reg_end" id="reg-end-value"><input type="hidden" name="end_date" id="end-date-value">
<section data-step="1" class="space-y-5 rounded-2xl border bg-white p-4 shadow-sm sm:p-6">
<div><p class="text-xs font-bold text-indigo-600">步驟 1</p><h2 class="text-xl font-bold">賽事基本資料</h2></div>
<div class="grid gap-4 sm:grid-cols-2">
<label class="sm:col-span-2 text-sm font-medium">賽事名稱 *<input name="name" required maxlength="120" value="{{ old('name') }}" class="mt-1 min-h-12 w-full rounded-xl px-3" placeholder="例如：2026 百川射箭公開賽"></label>
<label class="sm:col-span-2 text-sm font-medium">主辦單位 *<input name="organizer" required maxlength="120" value="{{ old('organizer', $organizerName) }}" class="mt-1 min-h-12 w-full rounded-xl px-3" placeholder="主辦單位名稱"></label>
<label class="sm:col-span-2 text-sm font-medium">比賽場地<div class="mt-2 grid grid-cols-2 gap-3"><span class="choice rounded-xl border p-4"><input type="radio" name="mode" value="outdoor" @checked(old('mode','outdoor')==='outdoor')> <strong class="ml-2">室外賽事</strong><small class="mt-1 block pl-6 text-gray-500">70m、50m、30m</small></span><span class="choice rounded-xl border p-4"><input type="radio" name="mode" value="indoor" @checked(old('mode')==='indoor')> <strong class="ml-2">室內賽事</strong><small class="mt-1 block pl-6 text-gray-500">18m</small></span></div></label>
<label class="text-sm font-medium">比賽日期 *<input type="date" id="start-date" name="start_date" required value="{{ old('start_date') }}" class="mt-1 min-h-12 w-full rounded-xl px-3"></label><label class="text-sm font-medium">場地名稱（選填）<input name="venue" value="{{ old('venue') }}" class="mt-1 min-h-12 w-full rounded-xl px-3" placeholder="例如：市立射箭場"></label>
</div>
<details class="rounded-xl border px-4"><summary class="flex min-h-12 cursor-pointer items-center justify-between font-semibold">日期與報名設定 <span>⌄</span></summary><div class="grid gap-4 border-t py-4 sm:grid-cols-2">
<label class="text-sm font-medium">賽事天數<select name="date_rule" id="date-rule" class="mt-1 min-h-12 w-full rounded-xl px-3"><option value="single">單日賽事</option><option value="multi">多日賽事</option></select></label><label id="custom-end-wrap" class="hidden text-sm font-medium">結束日期<input type="date" name="custom_end_date" id="custom-end" class="mt-1 min-h-12 w-full rounded-xl px-3"></label>
<label class="text-sm font-medium">報名開始<select name="reg_start_rule" id="reg-start-rule" class="mt-1 min-h-12 w-full rounded-xl px-3"><option value="immediate">建立後立即開放</option><option value="scheduled">指定時間</option></select></label><label id="scheduled-start-wrap" class="hidden text-sm font-medium">開始時間<input type="datetime-local" name="scheduled_reg_start" id="scheduled-start" class="mt-1 min-h-12 w-full rounded-xl px-3"></label>
<label class="text-sm font-medium">報名截止<select name="reg_end_rule" id="reg-end-rule" class="mt-1 min-h-12 w-full rounded-xl px-3"><option value="previous_day">比賽前一天 23:59</option><option value="same_day">比賽當天 23:59</option><option value="custom">自訂時間</option></select></label><label id="custom-reg-end-wrap" class="hidden text-sm font-medium">截止時間<input type="datetime-local" name="custom_reg_end" id="custom-reg-end" class="mt-1 min-h-12 w-full rounded-xl px-3"></label>
</div></details>
<div><p class="mb-2 text-sm font-medium">比賽形式</p><div class="grid gap-2 sm:grid-cols-3">@foreach(['qualification'=>'只有排名賽','qualification_elimination'=>'排名賽後可建立對抗賽','elimination_only'=>'只有對抗賽'] as $value=>$label)<label class="choice flex min-h-16 items-center gap-2 rounded-xl border px-4"><input type="radio" name="competition_format" value="{{ $value }}" @checked(old('competition_format','qualification')===$value)><strong>{{ $label }}</strong></label>@endforeach</div></div>
<div><p class="mb-2 text-sm font-medium">誰可以找到這場賽事？</p><div class="grid gap-2 sm:grid-cols-2"><label class="choice flex min-h-14 items-center gap-2 rounded-xl border px-4"><input type="radio" name="visibility" value="unlisted" checked><span><strong>僅限取得連結的人</strong><small class="block text-gray-500">不顯示於公開列表</small></span></label>@if($canChoosePublicVisibility)<label class="choice flex min-h-14 items-center gap-2 rounded-xl border px-4"><input type="radio" name="visibility" value="public"><span><strong>公開賽事</strong><small class="block text-gray-500">可被搜尋及瀏覽</small></span></label>@endif</div></div>
<button type="button" data-next="2" class="min-h-12 w-full rounded-xl bg-indigo-600 font-semibold text-white">下一步：設定組別</button>
</section>
<section data-step="2" class="hidden space-y-5 rounded-2xl border bg-white p-4 shadow-sm sm:p-6">
<div><p class="text-xs font-bold text-indigo-600">步驟 2</p><h2 class="text-xl font-bold">建立參賽組別</h2></div>
<div><p class="mb-2 text-sm font-medium">選擇比賽項目</p><div id="activity-options" class="grid gap-2 sm:grid-cols-2"></div></div>
<div><p class="mb-2 text-sm font-medium">組別分類</p><div class="grid grid-cols-3 gap-2">@foreach(['open'=>'公開組','male'=>'男子組','female'=>'女子組'] as $value=>$label)<label class="choice flex min-h-12 items-center justify-center gap-2 rounded-xl border px-2"><input type="checkbox" class="gender-option" value="{{ $value }}" @checked($value==='open')> {{ $label }}</label>@endforeach</div></div>
<div id="ranking-format-wrap"><p class="mb-2 text-sm font-medium">排名賽賽制</p><div class="grid gap-2 sm:grid-cols-3"><label class="choice rounded-xl border p-3"><input type="radio" name="round_format" value="single" checked> <strong>單局</strong><small id="single-summary" class="mt-1 block pl-6 text-gray-500"></small></label><label class="choice rounded-xl border p-3"><input type="radio" name="round_format" value="double"> <strong>雙局</strong><small id="double-summary" class="mt-1 block pl-6 text-gray-500"></small></label><label class="choice rounded-xl border p-3"><input type="radio" name="round_format" value="custom"> <strong>自訂</strong><small class="mt-1 block pl-6 text-gray-500">進階箭數設定</small></label></div>
<div id="custom-format" class="mt-3 hidden grid gap-3 rounded-xl bg-gray-50 p-3 sm:grid-cols-3"><label class="text-sm">局數<input id="custom-rounds" type="number" min="1" max="4" value="1" class="mt-1 min-h-11 w-full rounded-lg px-3"></label><label class="text-sm">每局箭數<input id="custom-arrows" type="number" min="6" max="72" step="3" value="36" class="mt-1 min-h-11 w-full rounded-lg px-3"></label><label class="text-sm">每趟箭數<select id="custom-per-end" class="mt-1 min-h-11 w-full rounded-lg px-3"><option value="3">3 箭</option><option value="6" selected>6 箭</option></select></label><p id="custom-format-summary" class="sm:col-span-3 text-sm font-semibold text-indigo-700"></p></div></div>
<div><div class="mb-2 flex items-center justify-between"><p class="text-sm font-medium">組別預覽</p><button type="button" id="apply-quota" class="text-sm font-semibold text-indigo-600">全部設定名額</button></div><div id="group-preview" class="space-y-2"></div><p id="group-error" class="mt-2 hidden text-sm font-semibold text-red-600"></p></div>
<div class="grid grid-cols-2 gap-3"><button type="button" data-back="1" class="min-h-12 rounded-xl border font-semibold">上一步</button><button type="button" data-next="3" class="min-h-12 rounded-xl bg-indigo-600 font-semibold text-white">檢查並確認</button></div>
</section>
<section data-step="3" class="hidden space-y-5 rounded-2xl border bg-white p-4 shadow-sm sm:p-6"><div><p class="text-xs font-bold text-indigo-600">步驟 3</p><h2 class="text-xl font-bold">確認建立賽事</h2></div><div id="confirmation" class="divide-y rounded-xl border"></div><p class="rounded-xl bg-indigo-50 p-3 text-sm font-medium text-indigo-800">建立成功後會依設定立即開放或等待指定時間開放報名。</p><div class="grid grid-cols-2 gap-3"><button type="button" data-back="2" class="min-h-12 rounded-xl border font-semibold">返回修改</button><button type="submit" class="min-h-12 rounded-xl bg-emerald-600 font-semibold text-white">確認建立賽事</button></div></section>
</form></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('event-create'),steps=[...document.querySelectorAll('[data-step]')],progress=[...document.querySelectorAll('[data-progress]')],maxGroups=@js($maxGroups);let groups=[];const presets={outdoor:[['r70','反曲弓 70 公尺','recurve','70m'],['r30','反曲弓 30 公尺','recurve','30m'],['c50','複合弓 50 公尺','compound','50m'],['b30','裸弓 30 公尺','barebow','30m']],indoor:[['r18','反曲弓 18 公尺','recurve','18m'],['c18','複合弓 18 公尺','compound','18m'],['b18','裸弓 18 公尺','barebow','18m']]},genderNames={open:'公開組',male:'男子組',female:'女子組'},q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],mode=()=>q('[name=mode]:checked').value,competition=()=>q('[name=competition_format]:checked').value,esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const show=n=>{steps.forEach(x=>x.classList.toggle('hidden',+x.dataset.step!==n));progress.forEach(x=>{const on=+x.dataset.progress===n;x.classList.toggle('bg-indigo-600',on);x.classList.toggle('text-white',on);x.classList.toggle('bg-gray-100',!on);x.classList.toggle('text-gray-500',!on)});scrollTo({top:0,behavior:'smooth'})};
function syncDates(){const start=q('#start-date').value;if(!start)return;const d=new Date(start+'T12:00:00');q('#end-date-value').value=q('#date-rule').value==='multi'?q('#custom-end').value:start;q('#reg-start-value').value=q('#reg-start-rule').value==='scheduled'?q('#scheduled-start').value:'';if(q('#reg-end-rule').value==='custom')q('#reg-end-value').value=q('#custom-reg-end').value;else{if(q('#reg-end-rule').value==='previous_day'&&new Date().toDateString()!==d.toDateString())d.setDate(d.getDate()-1);q('#reg-end-value').value=d.toISOString().slice(0,10)+'T23:59'}}
function syncConditional(){const multi=q('#date-rule').value==='multi',scheduled=q('#reg-start-rule').value==='scheduled',customEnd=q('#reg-end-rule').value==='custom';q('#custom-end-wrap').classList.toggle('hidden',!multi);q('#custom-end').required=multi;q('#scheduled-start-wrap').classList.toggle('hidden',!scheduled);q('#scheduled-start').required=scheduled;q('#custom-reg-end-wrap').classList.toggle('hidden',!customEnd);q('#custom-reg-end').required=customEnd;q('#ranking-format-wrap').classList.toggle('hidden',competition()==='elimination_only');syncDates()}
function renderActivities(){q('#activity-options').innerHTML=presets[mode()].map(p=>`<label class="choice flex min-h-14 items-center gap-3 rounded-xl border px-4"><input type="checkbox" class="activity-option" value="${p[0]}"><strong>${p[1]}</strong></label>`).join('');qa('.activity-option').forEach(x=>x.addEventListener('change',buildGroups));syncFormatLabels();buildGroups()}
function formatData(){const indoor=mode()==='indoor',format=q('[name=round_format]:checked')?.value||'single',single=indoor?30:36,per=indoor?3:6;if(format==='double')return{arrows:single*2,per};if(format==='custom')return{arrows:+q('#custom-rounds').value*+q('#custom-arrows').value,per:+q('#custom-per-end').value};return{arrows:single,per}}
function syncFormatLabels(){const single=mode()==='indoor'?30:36;q('#single-summary').textContent=`${single} 箭`;q('#double-summary').textContent=`${single*2} 箭，分上下局`;const d=formatData(),valid=d.arrows%Math.max(1,d.per)===0;q('#custom-format-summary').textContent=`全場 ${d.arrows} 箭・共 ${valid?d.arrows/d.per:'—'} 趟${valid?'':'（箭數無法整除）'}`;q('#custom-format-summary').classList.toggle('text-red-600',!valid)}
function buildGroups(){const selected=qa('.activity-option:checked').map(x=>x.value),genders=qa('.gender-option:checked').map(x=>x.value),old=Object.fromEntries(groups.map(g=>[g.key,g.quota]));groups=[];selected.forEach(key=>{const p=presets[mode()].find(x=>x[0]===key);genders.forEach(g=>groups.push({key:key+'-'+g,name:p[1]+genderNames[g],bow:p[2],distance:p[3],gender:g,quota:old[key+'-'+g]??''}))});renderGroups()}
function renderGroups(){const d=formatData();q('#group-preview').innerHTML=groups.length?groups.map((g,i)=>`<article class="grid gap-3 rounded-xl border p-3 sm:grid-cols-[1fr_9rem_auto] sm:items-center"><strong>${g.name}</strong><label class="text-xs text-gray-500">名額（留空不限）<input data-quota="${g.key}" type="number" min="1" value="${g.quota}" class="mt-1 min-h-10 w-full rounded-lg px-2"></label><button type="button" data-remove="${g.key}" class="min-h-10 px-3 text-sm font-semibold text-red-600">移除</button><input type="hidden" name="groups[${i}][name]" value="${g.name}"><input type="hidden" name="groups[${i}][bow_type]" value="${g.bow}"><input type="hidden" name="groups[${i}][gender]" value="${g.gender}"><input type="hidden" name="groups[${i}][distance]" value="${g.distance}"><input type="hidden" name="groups[${i}][arrow_count]" value="${d.arrows}"><input type="hidden" name="groups[${i}][arrows_per_end]" value="${d.per}"><input type="hidden" name="groups[${i}][fee]" value="0"><input data-quota-hidden="${g.key}" type="hidden" name="groups[${i}][quota]" value="${g.quota}"></article>`).join(''):'<p class="rounded-xl border border-dashed p-6 text-center text-sm text-gray-500">請先選擇至少一個比賽項目與分類。</p>';qa('[data-quota]').forEach(x=>x.addEventListener('input',()=>{groups.find(g=>g.key===x.dataset.quota).quota=x.value;q(`[data-quota-hidden="${x.dataset.quota}"]`).value=x.value}));qa('[data-remove]').forEach(x=>x.addEventListener('click',()=>{groups=groups.filter(g=>g.key!==x.dataset.remove);renderGroups()}));const over=maxGroups!==null&&groups.length>maxGroups;q('#group-error').textContent=over?`目前最多可建立 ${maxGroups} 個組別，請移除部分組合。`:'';q('#group-error').classList.toggle('hidden',!over)}
function validateStep1(){syncDates();for(const s of ['[name=name]','[name=organizer]','#start-date'])if(!q(s).reportValidity())return false;if(q('#date-rule').value==='multi'&&!q('#custom-end').value)return q('#custom-end').reportValidity();if(q('#reg-start-rule').value==='scheduled'&&!q('#scheduled-start').value)return q('#scheduled-start').reportValidity();if(q('#reg-end-rule').value==='custom'&&!q('#custom-reg-end').value)return q('#custom-reg-end').reportValidity();return true}
function confirmation(){syncDates();const labels={qualification:'只有排名賽',qualification_elimination:'排名賽後可建立對抗賽',elimination_only:'只有對抗賽'},visibility=q('[name=visibility]:checked')?.value==='public'?'公開賽事':'連結限定';q('#confirmation').innerHTML=`<div class="p-4"><small class="text-gray-500">賽事</small><p class="font-semibold">${esc(q('[name=name]').value)}</p><p class="text-sm text-gray-600">${esc(q('[name=organizer]').value)}・${mode()==='indoor'?'室內':'室外'}・${esc(q('#start-date').value)}</p></div><div class="p-4"><small class="text-gray-500">比賽形式</small><p class="font-semibold">${labels[competition()]}</p><p class="text-sm text-gray-600">${visibility}</p></div><div class="p-4"><small class="text-gray-500">組別</small><p class="font-semibold">共 ${groups.length} 組</p><p class="text-sm text-gray-600">${groups.map(g=>esc(g.name)).join('、')}</p></div>`}
qa('[data-next]').forEach(b=>b.addEventListener('click',()=>{const n=+b.dataset.next;if(n===2&&!validateStep1())return;if(n===3){const d=formatData();if(!groups.length||(maxGroups!==null&&groups.length>maxGroups)){q('#group-error').classList.remove('hidden');return}if(d.arrows%d.per!==0){q('#group-error').textContent='自訂賽制的總箭數必須能被每趟箭數整除。';q('#group-error').classList.remove('hidden');return}confirmation()}show(n)}));qa('[data-back]').forEach(b=>b.addEventListener('click',()=>show(+b.dataset.back)));qa('[name=mode]').forEach(x=>x.addEventListener('change',renderActivities));qa('[name=competition_format]').forEach(x=>x.addEventListener('change',syncConditional));qa('.gender-option').forEach(x=>x.addEventListener('change',buildGroups));qa('[name=round_format]').forEach(x=>x.addEventListener('change',()=>{q('#custom-format').classList.toggle('hidden',q('[name=round_format]:checked').value!=='custom');syncFormatLabels();renderGroups()}));['#custom-rounds','#custom-arrows','#custom-per-end'].forEach(s=>q(s).addEventListener('input',()=>{syncFormatLabels();renderGroups()}));['#start-date','#date-rule','#custom-end','#reg-start-rule','#scheduled-start','#reg-end-rule','#custom-reg-end'].forEach(s=>q(s).addEventListener('change',syncConditional));q('#apply-quota').addEventListener('click',()=>{const value=prompt('所有組別統一名額（留空取消限制）','32');if(value===null)return;groups.forEach(g=>g.quota=value);renderGroups()});form.addEventListener('submit',e=>{syncDates();if(!groups.length)e.preventDefault()});syncConditional();renderActivities();show(1)});
</script>
@endsection
