@extends('layouts.app')
@section('title', '主辦方中心')
@section('content')
<div class="mx-auto max-w-6xl space-y-6 px-4 py-6 sm:px-6 sm:py-8">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-widest text-indigo-600">Organizer</p><h1 class="mt-1 text-2xl font-bold">我的賽事</h1></div>@if(auth()->user()->canCreateEvents())<a href="{{ route('organizer.events.create') }}" class="inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-indigo-600 px-5 text-sm font-medium text-white sm:w-auto">建立賽事</a>@else<a href="{{ route('organizer.qualification.show') }}" class="inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-red-600 px-5 text-sm font-medium text-white sm:w-auto">查看資格狀態</a>@endif</div>
    <div class="grid gap-4 md:grid-cols-2">@forelse($events as $event)<a href="{{ route('organizer.events.show',$event) }}" class="rounded-2xl border bg-white p-4 shadow-sm hover:border-indigo-300 sm:p-5"><div class="flex justify-between gap-3"><div class="min-w-0"><h2 class="break-words font-semibold">{{ $event->name }}</h2><p class="mt-1 text-sm text-gray-500">{{ $event->start_date->format('Y-m-d') }}～{{ $event->end_date->format('Y-m-d') }}</p></div><span class="h-fit shrink-0 rounded-full px-2 py-1 text-xs {{ $event->isPublished() ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600' }}">{{ ['draft'=>'草稿','pending'=>'待發布','approved'=>'已發布','rejected'=>'已下架','archived'=>'已封存'][$event->status] ?? $event->status }}</span></div><div class="mt-4 grid grid-cols-2 gap-2 border-t pt-3 text-center"><div class="rounded-xl bg-gray-50 p-2"><p class="text-lg font-semibold">{{ $event->groups_count }}</p><p class="text-xs text-gray-500">組別</p></div><div class="rounded-xl bg-gray-50 p-2"><p class="text-lg font-semibold">{{ $event->registrations_count }}</p><p class="text-xs text-gray-500">報名</p></div>@if($event->hasPlanFeature('check_in'))<div class="rounded-xl bg-gray-50 p-2"><p class="text-lg font-semibold">{{ $event->checked_in_count }}</p><p class="text-xs text-gray-500">已報到</p></div>@endif<div class="rounded-xl bg-gray-50 p-2"><p class="text-lg font-semibold">{{ $event->badges_count }}</p><p class="text-xs text-gray-500">Badge</p></div></div></a>@empty<p class="text-sm text-gray-500">尚無賽事</p>@endforelse</div>
    {{ $events->links() }}
</div>
@endsection
