@extends('layouts.app')
@section('title', $event->name.' 工作台')
@section('content')
<div class="mx-auto max-w-7xl space-y-7 px-4 py-8 sm:px-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('organizer.events.index') }}" class="text-sm text-indigo-600">← 我的賽事</a><h1 class="mt-2 text-2xl font-bold">{{ $event->name }}</h1><p class="mt-1 text-sm text-gray-500">{{ $event->organizer }}・{{ $event->start_date->format('Y-m-d') }}～{{ $event->end_date->format('Y-m-d') }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('events.show',$event) }}" class="rounded-xl border px-4 py-2 text-sm">預覽公開頁</a>@can('update',$event)<a href="{{ route('organizer.events.edit',$event) }}" class="rounded-xl border px-4 py-2 text-sm">編輯資料</a>@endcan</div></div>
@if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<section class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-sm text-gray-500">賽事狀態</p><p class="mt-1 font-semibold">{{ ['draft'=>'草稿','pending'=>'平台審核中','approved'=>'已核准發布','rejected'=>'平台退回','archived'=>'已封存'][$event->status] ?? $event->status }}</p>@if($event->review_note)<p class="mt-1 text-sm text-red-600">平台備註：{{ $event->review_note }}</p>@endif</div>@can('update',$event)<div class="flex gap-2">@if(in_array($event->status,['draft','rejected']))<form method="POST" action="{{ route('organizer.events.submit',$event) }}">@csrf<button class="rounded-xl bg-indigo-600 px-4 py-2 text-sm text-white">送交平台審核</button></form>@endif @if(!$event->cancelled_at)<form method="POST" action="{{ route('organizer.events.cancel',$event) }}" onsubmit="return confirm('確定取消賽事？')">@csrf<button class="rounded-xl border border-red-200 px-4 py-2 text-sm text-red-600">取消賽事</button></form>@endif</div>@endcan</div></section>
<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-2xl border bg-white p-4"><p class="text-xs text-gray-500">組別</p><p class="mt-1 text-2xl font-semibold">{{ $event->groups->count() }}</p></div><div class="rounded-2xl border bg-white p-4"><p class="text-xs text-gray-500">報名</p><p class="mt-1 text-2xl font-semibold">{{ $event->registrations_count }}</p></div><div class="rounded-2xl border bg-white p-4"><p class="text-xs text-gray-500">已報到</p><p class="mt-1 text-2xl font-semibold">{{ $statusCounts['checked_in'] ?? 0 }}</p></div><div class="rounded-2xl border bg-white p-4"><p class="text-xs text-gray-500">Badge</p><p class="mt-1 text-2xl font-semibold">{{ $event->badges_count }}</p></div></div>
<section><h2 class="mb-3 text-lg font-semibold">賽事管理</h2><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@can('manageGroups',$event)<a href="{{ route('events.groups.index',$event) }}" class="rounded-2xl border bg-white p-5 hover:border-indigo-300"><h3 class="font-semibold">組別與規則</h3><p class="mt-1 text-sm text-gray-500">名額、距離、箭數與報名期間</p></a>@endcan @can('manageRegistrations',$event)<a href="{{ route('organizer.events.registrations.index',$event) }}" class="rounded-2xl border bg-white p-5 hover:border-indigo-300"><h3 class="font-semibold">報名與報到</h3><p class="mt-1 text-sm text-gray-500">名單、繳費、狀態與 QR 報到</p></a>@endcan @can('manageScores',$event)<a href="{{ route('organizer.events.results.index',$event) }}" class="rounded-2xl border bg-white p-5 hover:border-indigo-300"><h3 class="font-semibold">成績與發布</h3><p class="mt-1 text-sm text-gray-500">確認選手成績與發布結果</p></a>@endcan <a href="{{ route('organizer.events.badges.index',$event) }}" class="rounded-2xl border bg-white p-5 hover:border-indigo-300"><h3 class="font-semibold">Badge 管理</h3><p class="mt-1 text-sm text-gray-500">申請 QR、審核與授予</p></a></div></section>
@can('manageStaff',$event)<section class="rounded-2xl border bg-white p-5"><h2 class="font-semibold">工作人員</h2><form method="POST" action="{{ route('organizer.events.staff.store',$event) }}" class="mt-4 flex flex-wrap gap-2">@csrf<input type="email" name="email" required class="min-w-56 flex-1 rounded-xl border-gray-300 text-sm" placeholder="已註冊會員 Email"><select name="role" class="rounded-xl border-gray-300 text-sm"><option value="manager">管理者</option><option value="staff">工作人員</option><option value="viewer">只讀</option></select><button class="rounded-xl bg-gray-900 px-4 py-2 text-sm text-white">加入</button></form><div class="mt-4 divide-y">@foreach($event->staff as $staff)<div class="flex items-center justify-between py-3 text-sm"><div><p class="font-medium">{{ $staff->user?->display_name }}</p><p class="text-xs text-gray-500">{{ $staff->role }}・{{ $staff->status }}</p></div>@if($staff->role!=='owner' && $staff->status==='active')<form method="POST" action="{{ route('organizer.events.staff.revoke',[$event,$staff]) }}">@csrf @method('PATCH')<button class="text-xs text-red-600">撤銷</button></form>@endif</div>@endforeach</div></section>@endcan
<section class="rounded-2xl border bg-white p-5"><h2 class="font-semibold">最近操作紀錄</h2><div class="mt-3 divide-y">@forelse($auditLogs as $log)<div class="flex items-center justify-between gap-4 py-3 text-sm"><div><p class="font-medium">{{ $log->action }}</p><p class="text-xs text-gray-500">{{ $log->user?->display_name ?? '系統' }}</p></div><time class="text-xs text-gray-500">{{ $log->created_at->format('Y-m-d H:i') }}</time></div>@empty<p class="text-sm text-gray-500">尚無操作紀錄。</p>@endforelse</div></section>
</div>
@endsection
