@extends('layouts.app')
@section('title', $event->name.' 工作台')
@section('content')
@php
    $hasScoring = $event->scoringSessions()->exists();
    $hasElimination = $event->eliminationBrackets()->exists();
    $rankingRegistrations = $event->registrations()->whereIn('status', ['registered', 'checked_in', 'no_show']);
    $publishedRankings = (clone $rankingRegistrations)->exists() && (clone $rankingRegistrations)->whereNull('result_published_at')->doesntExist();
    $showEliminationStage = $event->hasPlanFeature('individual_elimination') || $hasElimination;
    $statusLabel = $officiallyCompleted ? '已完成' : ($event->cancelled_at ? '已取消' : match ($event->status) {
        'draft', 'pending' => '草稿', 'rejected' => '已下架', 'archived' => '已封存',
        default => $completionCheck['ready'] ? '可完成賽事' : ($hasElimination && $publishedRankings ? '對抗賽進行中' : ($hasScoring ? '排名賽進行中' : '報名中')),
    });
    $stageClass = fn (bool $done, bool $active) => $done ? 'bg-emerald-600 text-white border-emerald-600' : ($active ? 'bg-indigo-600 text-white border-indigo-600' : 'bg-white text-gray-400 border-gray-200');
@endphp
<div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8" x-data="{ tab: ['overview','execute','manage'].includes(location.hash.slice(1)) ? location.hash.slice(1) : 'overview' }">
    <header class="flex items-center justify-between gap-3">
        <div class="min-w-0"><a href="{{ route('organizer.events.index') }}" class="inline-flex min-h-10 items-center text-sm font-medium text-indigo-600">← 我的主辦賽事</a><h1 class="truncate text-2xl font-bold">{{ $event->name }}</h1></div>
        <details class="relative shrink-0"><summary class="flex h-11 w-11 cursor-pointer list-none items-center justify-center rounded-xl border bg-white text-xl">⋯</summary><div class="absolute right-0 z-30 mt-2 w-56 overflow-hidden rounded-xl border bg-white p-2 shadow-xl"><a href="{{ route('events.show',$event) }}" class="flex min-h-11 items-center rounded-lg px-3 text-sm hover:bg-gray-50">{{ $officiallyCompleted ? '查看正式成績' : ($event->isPublished() ? '查看賽事頁' : '預覽草稿') }}</a>@can('update',$event)@if(!$officiallyCompleted && !$event->cancelled_at)<a href="{{ route('organizer.events.edit',$event) }}" class="flex min-h-11 items-center rounded-lg px-3 text-sm hover:bg-gray-50">編輯資料</a>@endif @endcan</div></details>
    </header>
    @if(session('success'))<div class="mt-4 rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif

    <nav class="mt-5 grid grid-cols-3 rounded-2xl bg-gray-100 p-1" aria-label="賽事工作台">@foreach(['overview'=>'總覽','execute'=>'執行','manage'=>'管理'] as $key=>$label)<button type="button" @click="tab='{{ $key }}'; history.replaceState(null, '', '#{{ $key }}')" :class="tab==='{{ $key }}' ? 'bg-white text-gray-950 shadow-sm' : 'text-gray-500'" class="min-h-12 rounded-xl text-sm font-semibold">{{ $label }}</button>@endforeach</nav>

    <main class="mt-5">
        <div x-show="tab==='overview'" x-cloak class="space-y-5">
            <section class="rounded-2xl border bg-white p-5 shadow-sm">
                <div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs text-gray-400">目前狀態</p><h2 class="mt-1 text-xl font-bold {{ $officiallyCompleted ? 'text-emerald-700' : '' }}">{{ $statusLabel }}</h2>@if($event->cancelled_at && $event->review_note)<p class="mt-1 text-sm text-gray-500">{{ $event->review_note }}</p>@endif</div>@if($event->isPublished() && !$officiallyCompleted)<span class="rounded-full px-3 py-1 text-xs font-medium {{ $event->visibility === 'unlisted' ? 'bg-slate-100 text-slate-600' : 'bg-emerald-100 text-emerald-700' }}">{{ $event->visibility === 'unlisted' ? '非公開' : '公開' }}</span>@endif</div>
                @php
                    $stages = [['建立', true, !$event->isPublished()], ['報名', $hasScoring || $publishedRankings, $event->isPublished() && !$hasScoring], ['排名', $publishedRankings, $hasScoring && !$publishedRankings]];
                    if ($showEliminationStage) $stages[] = ['對抗', $hasElimination && $completionCheck['ready'], $hasElimination && $publishedRankings && !$completionCheck['ready']];
                    $stages[] = ['完成', $officiallyCompleted, $completionCheck['ready'] && !$officiallyCompleted];
                @endphp
                <div class="mt-6 flex items-start">@foreach($stages as [$label, $done, $active])<div class="relative flex flex-1 flex-col items-center text-center">@if(!$loop->first)<span class="absolute right-1/2 top-4 h-0.5 w-full {{ $done || $active ? 'bg-indigo-300' : 'bg-gray-200' }}"></span>@endif<span class="relative z-10 flex h-8 w-8 items-center justify-center rounded-full border text-xs font-bold {{ $stageClass($done, $active) }}">{{ $done ? '✓' : $loop->iteration }}</span><span class="mt-2 text-xs font-medium {{ $active ? 'text-indigo-700' : ($done ? 'text-emerald-700' : 'text-gray-400') }}">{{ $label }}</span></div>@endforeach</div>
            </section>
            @if($nextAction)<section class="rounded-2xl bg-indigo-600 p-5 text-white shadow-sm"><h2 class="text-lg font-bold">{{ $nextAction['title'] }}</h2><div class="mt-4">@if(($nextAction['method'] ?? 'GET') === 'POST')<form method="POST" action="{{ $nextAction['url'] }}" onsubmit="return confirm('{{ $nextAction['label'] }}？')">@csrf<button class="min-h-12 w-full rounded-xl bg-white px-5 text-sm font-bold text-indigo-700 sm:w-auto">{{ $nextAction['label'] }}</button></form>@else<a href="{{ $nextAction['url'] }}" class="inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-white px-5 text-sm font-bold text-indigo-700 sm:w-auto">{{ $nextAction['label'] }} →</a>@endif</div></section>@endif
            @if(!$officiallyCompleted && $event->isPublished() && !$completionCheck['ready'] && auth()->user()->can('update', $event))<details class="rounded-2xl border bg-white px-4 py-2"><summary class="flex min-h-12 cursor-pointer list-none items-center justify-between text-sm font-semibold"><span>待處理項目</span><span class="rounded-full bg-amber-100 px-2 py-1 text-xs text-amber-700">{{ count($completionCheck['blockers']) }}</span></summary><ul class="space-y-2 border-t py-3">@foreach($completionCheck['blockers'] as $blocker)<li class="text-sm text-gray-600">• {{ $blocker }}</li>@endforeach</ul></details>@endif
        </div>

        <div x-show="tab==='execute'" x-cloak class="overflow-hidden rounded-2xl border bg-white px-4 shadow-sm sm:px-5"><div class="divide-y">
            @can('manageRegistrations',$event)<a href="{{ route('organizer.events.registrations.index',$event) }}" class="flex min-h-16 items-center justify-between gap-3"><span class="font-semibold">報名與繳費</span><span class="flex items-center gap-3 text-sm text-gray-500">{{ $event->active_registrations_count }} 人 @if($event->pending_payments_count)<b class="text-amber-600">待繳 {{ $event->pending_payments_count }}</b>@endif <b>›</b></span></a>@endcan
            @if($event->requiresCheckIn())@can('manageRegistrations',$event)<a href="{{ route('organizer.events.check-in.index',$event) }}" class="flex min-h-16 items-center justify-between"><span class="font-semibold">現場報到</span><span class="text-sm text-gray-500">{{ $statusCounts['checked_in'] ?? 0 }} 人　›</span></a>@endcan @endif
            @can('manageScores',$event)<a href="{{ route('organizer.events.scoring.index',$event) }}" class="flex min-h-16 items-center justify-between"><span class="font-semibold">靶位與計分</span><span class="text-gray-400">›</span></a>@endcan
            @can('manageJudging',$event)<a href="{{ route('organizer.events.judging.index',$event) }}" class="flex min-h-16 items-center justify-between"><span class="font-semibold">裁判工作台</span><span class="text-gray-400">›</span></a>@endcan
            @can('viewResults',$event)<a href="{{ route('organizer.events.results.index',$event) }}" class="flex min-h-16 items-center justify-between"><span class="font-semibold">成績核對與發布</span><span class="text-sm text-gray-500">已核准 {{ $event->verified_results_count }}　›</span></a>@endcan
            @can('viewResults',$event)@if($event->hasPlanFeature('individual_elimination') || $event->canUpgradeToEventPass())<a href="{{ $event->hasPlanFeature('individual_elimination') ? route('organizer.events.elimination.index',$event) : route('store.index', ['event'=>$event->uuid]) }}" class="flex min-h-16 items-center justify-between"><span class="font-semibold">對抗賽管理</span><span class="text-sm text-gray-500">@unless($event->hasPlanFeature('individual_elimination'))升級　@endunless›</span></a>@endif @endcan
        </div></div>

        <div x-show="tab==='manage'" x-cloak class="space-y-5">
            <section class="overflow-hidden rounded-2xl border bg-white px-4 shadow-sm sm:px-5"><div class="divide-y">
                @can('manageGroups',$event)<a href="{{ route('events.groups.index',$event) }}" class="flex min-h-16 items-center justify-between"><span class="font-semibold">組別管理</span><span class="text-sm text-gray-500">{{ $event->groups->count() }} 組　›</span></a>@endcan
                @if(auth()->user()->isAdmin() || auth()->user()->can('manageStaff',$event))<a href="{{ route('organizer.events.badges.index',$event) }}" class="flex min-h-16 items-center justify-between"><span class="font-semibold">Badge 管理</span><span class="text-sm text-gray-500">{{ $event->badges_count }} 枚　›</span></a>@endif
                @can('update',$event)@if(!$officiallyCompleted && !$event->cancelled_at)<a href="{{ route('organizer.events.edit',$event) }}" class="flex min-h-16 items-center justify-between"><span class="font-semibold">編輯資料</span><span class="text-gray-400">›</span></a>@endif @endcan
                <a href="{{ route('events.show',$event) }}" class="flex min-h-16 items-center justify-between"><span class="font-semibold">{{ $officiallyCompleted ? '查看正式成績' : '查看賽事頁' }}</span><span class="text-gray-400">›</span></a>
            </div></section>
            @if($event->isPublished() && !$officiallyCompleted)<section class="rounded-2xl border bg-white p-4 shadow-sm" x-data="{ copied:false, url:@js(route('events.show',$event)), title:@js($event->name) }"><div class="grid grid-cols-2 gap-2"><button type="button" @click="navigator.clipboard.writeText(url); copied=true; setTimeout(()=>copied=false,1600)" class="min-h-12 rounded-xl bg-indigo-600 text-sm font-semibold text-white"><span x-show="!copied">複製連結</span><span x-show="copied">已複製</span></button><button type="button" @click="navigator.share ? navigator.share({title,url}) : navigator.clipboard.writeText(url)" class="min-h-12 rounded-xl border text-sm font-semibold">分享</button></div></section>@endif

            @can('manageStaff',$event)<details class="rounded-2xl border bg-white px-4 py-2 shadow-sm" x-data="{ inviteRole:'staff' }"><summary class="flex min-h-12 cursor-pointer list-none items-center justify-between font-semibold"><span>工作人員</span><span class="text-sm text-gray-500">{{ $event->staff->where('status','active')->count() }} 人　⌄</span></summary><div class="grid gap-5 border-t py-4 md:grid-cols-2"><div><select x-model="inviteRole" class="min-h-12 w-full rounded-xl border-gray-300"><option value="manager">管理者</option><option value="staff">工作人員</option><option value="score_manager">成績管理員</option><option value="judge">裁判</option><option value="chief_judge">主裁判</option><option value="volunteer">志工</option><option value="viewer">只讀</option></select><div class="mt-3 flex justify-center">@foreach($staffInviteQrs as $role=>$qr)<img x-show="inviteRole==='{{ $role }}'" src="{{ $qr }}" alt="工作人員邀請 QR Code" class="h-52 w-52">@endforeach</div><details class="mt-3 rounded-xl border px-3"><summary class="flex min-h-11 cursor-pointer items-center text-sm font-medium">手動輸入 Email 加入</summary><form method="POST" action="{{ route('organizer.events.staff.store',$event) }}" class="grid gap-2 border-t py-3">@csrf<input type="email" name="email" required class="min-h-12 rounded-xl border-gray-300" placeholder="會員 Email"><select name="role" class="min-h-12 rounded-xl border-gray-300"><option value="manager">管理者</option><option value="staff">工作人員</option><option value="score_manager">成績管理員</option><option value="judge">裁判</option><option value="chief_judge">主裁判</option><option value="volunteer">志工</option><option value="viewer">只讀</option></select><button class="min-h-12 rounded-xl bg-gray-900 text-sm text-white">加入</button></form></details></div><div class="divide-y">@foreach($event->staff as $staff)<div class="flex min-h-16 items-center justify-between gap-3 py-2 text-sm"><div><p class="font-medium">{{ $staff->user?->display_name }}</p><p class="text-xs text-gray-500">{{ ['owner'=>'擁有者','manager'=>'管理者','staff'=>'工作人員','score_manager'=>'成績管理員','judge'=>'裁判','chief_judge'=>'主裁判','volunteer'=>'志工','viewer'=>'只讀'][$staff->role] ?? $staff->role }}</p></div>@if($staff->role!=='owner' && $staff->status==='active')<form method="POST" action="{{ route('organizer.events.staff.revoke',[$event,$staff]) }}">@csrf @method('PATCH')<button class="min-h-11 px-3 text-xs text-red-600">撤銷</button></form>@endif</div>@endforeach</div></div></details>@endcan
            @can('viewAuditLogs',$event)<details class="rounded-2xl border bg-white px-4 py-2 shadow-sm"><summary class="flex min-h-12 cursor-pointer list-none items-center justify-between font-semibold"><span>最近操作紀錄</span><span class="text-sm text-gray-500">{{ $auditLogs->count() }} 筆　⌄</span></summary><div class="divide-y border-t">@forelse($auditLogs as $log)<div class="flex items-center justify-between gap-3 py-3 text-sm"><span>{{ $log->action }}</span><time class="text-xs text-gray-500">{{ $log->created_at->format('Y-m-d H:i') }}</time></div>@empty<p class="py-3 text-sm text-gray-500">尚無紀錄</p>@endforelse</div></details>@endcan
            @can('update',$event)@if(!$officiallyCompleted && !$event->cancelled_at)<details class="rounded-2xl border border-red-100 bg-white px-4 py-2"><summary class="flex min-h-12 cursor-pointer list-none items-center justify-between font-semibold"><span>賽事狀態</span><span class="text-gray-400">⌄</span></summary><div class="grid gap-3 border-t py-3 sm:grid-cols-2">@if($event->isPublished())<form method="POST" action="{{ route('organizer.events.unpublish',$event) }}" onsubmit="return confirm('暫停公開後將停止新報名，既有資料會完整保留。確定繼續？')">@csrf<button class="min-h-12 w-full rounded-xl border border-amber-300 text-sm font-semibold text-amber-700">暫停公開</button></form>@else<form method="POST" action="{{ route('organizer.events.submit',$event) }}" onsubmit="return confirm('確定重新發布並開放報名？')">@csrf<button class="min-h-12 w-full rounded-xl bg-indigo-600 text-sm font-semibold text-white">重新發布</button></form>@endif<form method="POST" action="{{ route('organizer.events.cancel',$event) }}" class="space-y-2 sm:col-span-2" onsubmit="return confirm('取消後將永久停止報名與比賽流程，確定取消賽事？')">@csrf<textarea name="cancellation_reason" required maxlength="500" rows="2" class="w-full rounded-xl border-gray-300 text-base" placeholder="取消原因"></textarea><button class="min-h-12 w-full rounded-xl border border-red-300 text-sm font-semibold text-red-600">取消賽事</button></form></div></details>@endif @endcan
        </div>
    </main>
</div>
@endsection
